name: free_trade_zone
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - alabaster=0.7.16
  - atomicwrites=1.4.0
  - attrs=24.2.0
  - babel=2.11.0
  - black=24.8.0
  - blas=1.0
  - bottleneck=1.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.9.24
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - click=8.1.7
  - commonmark=0.9.1
  - contourpy=1.2.0
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - docutils=0.18.1
  - et_xmlfile=1.1.0
  - expat=2.6.3
  - flake8=7.1.1
  - fontconfig=2.14.1
  - fonttools=4.51.0
  - freetype=2.12.1
  - future=1.0.0
  - glib=2.78.4
  - glib-tools=2.78.4
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - hypothesis=6.115.6
  - icu=73.1
  - idna=3.7
  - imagesize=1.4.1
  - iniconfig=1.1.1
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - jpeg=9e
  - js2py=0.74
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lark=1.1.2
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libabseil=20240116.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libcurl=8.9.1
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libglib=2.78.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libpq=17.0
  - libprotobuf=4.25.3
  - libssh2=1.11.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.13.5
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - markupsafe=2.1.3
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - mccabe=0.7.0
  - mdurl=0.1.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mypy=1.11.2
  - mypy_extensions=1.0.0
  - mysql=8.4.0
  - ncurses=6.4
  - networkx=3.3
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openpyxl=3.1.5
  - openssl=3.0.15
  - packaging=24.1
  - pandas=2.2.2
  - pathspec=0.10.3
  - pcre2=10.42
  - pillow=11.0.0
  - pip=24.2
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - ply=3.11
  - psutil=5.9.0
  - pycodestyle=2.12.1
  - pyflakes=3.2.0
  - pygments=2.15.1
  - pyjsparser=2.7.1
  - pyparsing=3.2.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - pytest=7.4.4
  - python=3.11.10
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytz=2024.1
  - pyyaml=6.0.2
  - qt-main=5.15.2
  - readline=8.2
  - recommonmark=0.6.0
  - regex=2024.9.11
  - requests=2.32.3
  - rich=13.7.1
  - setuptools=75.1.0
  - sip=6.7.12
  - six=1.16.0
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - sphinx=7.3.7
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.10
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - tornado=6.4.1
  - typing=3.10.0.0
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024b
  - tzlocal=5.2
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - z3-solver==4.13.3.0
#prefix: /home/germankux/anaconda3/envs/free_trade_zone
